# Generated by Django 4.2.16 on 2024-09-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='intents',
        ),
    ]
